name: 記事を更新

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i
      - name: 記事を更新
        run: |
          echo '${{ secrets.GIMONFU_JSON }}' > .gimonfu.json
          pnpm replace-images
          pnpm gimonfu push
          pnpm format
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 変更をコミット
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: pages.mkizka.dev
